# Retail Sales Data Cleaning & Quality Analysis

This project focuses on understanding, assessing, cleaning, and validating a retail sales dataset before using it for analysis.

# 1. Dataset Overview

In [2]:
import pandas as pd
import numpy as np
from google.colab import files

# Upload the CSV file
uploaded = files.upload()

# Read the uploaded CSV file
df = pd.read_csv("online_retail_task2_students.csv")

# Display first 5 rows
df.head(30)

Saving online_retail_task2_students.csv to online_retail_task2_students (1).csv

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
1,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
2,536382,21832,CHOCOLATE CALCULATOR,12,2010-12-01 09:45:00,1.65,16098.0,United Kingdom
3,536390,22968,ROSE COTTAGE KEEPSAKE BOX,8,2010-12-01 10:19:00,8.50,17511.0,United Kingdom
4,536390,84030E,ENGLISH ROSE HOT WATER BOTTLE,24,2010-12-01 10:19:00,3.75,17511.0,United Kingdom
5,536390,22969,HOMEMADE JAM SCENTED CANDLES,96,2010-12-01 10:19:00,1.25,17511.0,United Kingdom
6,536393,22180,RETROSPOT LAMP,8,2010-12-01 10:37:00,9.95,13747.0,United Kingdom
7,536394,85152,HAND OVER THE CHOCOLATE SIGN,12,2010-12-01 10:39:00,2.10,13408.0,United Kingdom
8,536398,22111,SCOTTIE DOG HOT WATER BOTTLE,9,2010-12-01 10:52:00,4.95,13448.0,United Kingdom
9,536401,82581,TOILET METAL SIGN,2,2010-12-01 11:21:00,0.55,15862.0,United Kingdom
10,536401,20963,APPLE BATH SPONGE,1,2010-12-01 11:21:00,1.25,15862.0,United Kingdom
11,536401,22451,SILK PURSE BABUSHKA RED,1,2010-12-01 11:21:00,3.35,15862.0,United Kingdom
12,536401,22549,PICTURE DOMINOES,1,2010-12-01 11:21:00,1.45,15862.0,United Kingdom
13,536406,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 11:33:00,7.65,17850.0,United Kingdom
14,536408,22371,AIRLINE BAG VINTAGE TOKYO 78,4,2010-12-01 11:41:00,4.25,14307.0,United Kingdom
15,536408,21705,BAG 500g SWIRLY MARBLES,12,2010-12-01 11:41:00,1.65,14307.0,United Kingdom
16,536409,22197,SMALL POPCORN HOLDER,2,2010-12-01 11:45:00,0.85,17908.0,United Kingdom
17,536412,21738,COSY SLIPPER SHOES SMALL RED,5,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
18,536415,22910,PAPER CHAIN KIT VINTAGE CHRISTMAS,5,2010-12-01 11:57:00,2.95,12838.0,United Kingdom
19,536415,22086,PAPER CHAIN KIT 50'S CHRISTMAS,6,2010-12-01 11:57:00,2.95,12838.0,United Kingdom
20,536415,22899,CHILDREN'S APRON DOLLY GIRL,2,2010-12-01 11:57:00,2.10,12838.0,United Kingdom
21,536415,22739,RIBBON REEL CHRISTMAS SOCK BAUBLE,3,2010-12-01 11:57:00,1.65,12838.0,United Kingdom
22,536415,21212,PACK OF 72 RETROSPOT CAKE CASES,2,2010-12-01 11:57:00,0.55,12838.0,United Kingdom
23,536425,22768,FAMILY PHOTO FRAME CORNICE,2,2010-12-01 12:08:00,9.95,13758.0,United Kingdom
24,536437,22189,CREAM HEART CARD HOLDER,72,2010-12-01 12:12:00,3.39,13694.0,United Kingdom
25,536446,85172,HYACINTH BULB T-LIGHT CANDLES,32,2010-12-01 12:15:00,0.42,15983.0,United Kingdom
26,536446,20774,GREEN FERN NOTEBOOK,2,2010-12-01 12:15:00,1.65,15983.0,United Kingdom
27,536446,16016,LARGE CHINESE STYLE SCISSOR,10,2010-12-01 12:15:00,0.85,15983.0,United Kingdom
28,536446,21156,RETROSPOT CHILDRENS APRON,3,2010-12-01 12:15:00,1.95,15983.0,United Kingdom
29,536460,22926,IVORY GIANT GARDEN THERMOMETER,4,2010-12-01 12:22:00,5.95,14849.0,United Kingdom

In [3]:
df.shape

(20000, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    20000 non-null  object
 1   StockCode    20000 non-null  object
 2   Description  19950 non-null  object
 3   Quantity     20000 non-null  int64
 4   InvoiceDate  20000 non-null  object
 5   UnitPrice    20000 non-null  float64
 6   CustomerID   14851 non-null  float64
 7   Country      20000 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 1.2+ MB

In [6]:
df.head(30)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
1,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
2,536382,21832,CHOCOLATE CALCULATOR,12,2010-12-01 09:45:00,1.65,16098.0,United Kingdom
3,536390,22968,ROSE COTTAGE KEEPSAKE BOX,8,2010-12-01 10:19:00,8.50,17511.0,United Kingdom
4,536390,84030E,ENGLISH ROSE HOT WATER BOTTLE,24,2010-12-01 10:19:00,3.75,17511.0,United Kingdom
5,536390,22969,HOMEMADE JAM SCENTED CANDLES,96,2010-12-01 10:19:00,1.25,17511.0,United Kingdom
6,536393,22180,RETROSPOT LAMP,8,2010-12-01 10:37:00,9.95,13747.0,United Kingdom
7,536394,85152,HAND OVER THE CHOCOLATE SIGN,12,2010-12-01 10:39:00,2.10,13408.0,United Kingdom
8,536398,22111,SCOTTIE DOG HOT WATER BOTTLE,9,2010-12-01 10:52:00,4.95,13448.0,United Kingdom
9,536401,82581,TOILET METAL SIGN,2,2010-12-01 11:21:00,0.55,15862.0,United Kingdom
10,536401,20963,APPLE BATH SPONGE,1,2010-12-01 11:21:00,1.25,15862.0,United Kingdom
11,536401,22451,SILK PURSE BABUSHKA RED,1,2010-12-01 11:21:00,3.35,15862.0,United Kingdom
12,536401,22549,PICTURE DOMINOES,1,2010-12-01 11:21:00,1.45,15862.0,United Kingdom
13,536406,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 11:33:00,7.65,17850.0,United Kingdom
14,536408,22371,AIRLINE BAG VINTAGE TOKYO 78,4,2010-12-01 11:41:00,4.25,14307.0,United Kingdom
15,536408,21705,BAG 500g SWIRLY MARBLES,12,2010-12-01 11:41:00,1.65,14307.0,United Kingdom
16,536409,22197,SMALL POPCORN HOLDER,2,2010-12-01 11:45:00,0.85,17908.0,United Kingdom
17,536412,21738,COSY SLIPPER SHOES SMALL RED,5,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
18,536415,22910,PAPER CHAIN KIT VINTAGE CHRISTMAS,5,2010-12-01 11:57:00,2.95,12838.0,United Kingdom
19,536415,22086,PAPER CHAIN KIT 50'S CHRISTMAS,6,2010-12-01 11:57:00,2.95,12838.0,United Kingdom
20,536415,22899,CHILDREN'S APRON DOLLY GIRL,2,2010-12-01 11:57:00,2.10,12838.0,United Kingdom
21,536415,22739,RIBBON REEL CHRISTMAS SOCK BAUBLE,3,2010-12-01 11:57:00,1.65,12838.0,United Kingdom
22,536415,21212,PACK OF 72 RETROSPOT CAKE CASES,2,2010-12-01 11:57:00,0.55,12838.0,United Kingdom
23,536425,22768,FAMILY PHOTO FRAME CORNICE,2,2010-12-01 12:08:00,9.95,13758.0,United Kingdom
24,536437,22189,CREAM HEART CARD HOLDER,72,2010-12-01 12:12:00,3.39,13694.0,United Kingdom
25,536446,85172,HYACINTH BULB T-LIGHT CANDLES,32,2010-12-01 12:15:00,0.42,15983.0,United Kingdom
26,536446,20774,GREEN FERN NOTEBOOK,2,2010-12-01 12:15:00,1.65,15983.0,United Kingdom
27,536446,16016,LARGE CHINESE STYLE SCISSOR,10,2010-12-01 12:15:00,0.85,15983.0,United Kingdom
28,536446,21156,RETROSPOT CHILDRENS APRON,3,2010-12-01 12:15:00,1.95,15983.0,United Kingdom
29,536460,22926,IVORY GIANT GARDEN THERMOMETER,4,2010-12-01 12:22:00,5.95,14849.0,United Kingdom

In [7]:
df.tail(30)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
19970,581492,90208,PAIR OF PINK FLOWER CLUSTER SLIDE,1,2011-12-09 10:03:00,2.48,NaN,United Kingdom
19971,581492,21675,BUTTERFLIES STICKERS,2,2011-12-09 10:03:00,1.63,NaN,United Kingdom
19972,581492,22367,CHILDRENS APRON SPACEBOY DESIGN,1,2011-12-09 10:03:00,4.13,NaN,United Kingdom
19973,581492,23559,WOODLAND BUNNIES LOLLY MAKERS,5,2011-12-09 10:03:00,4.13,NaN,United Kingdom
19974,581492,82582,AREA PATROLLED METAL SIGN,1,2011-12-09 10:03:00,4.13,NaN,United Kingdom
19975,581496,21462,"NURSERY A,B,C PAINTED LETTERS",8,2011-12-09 10:20:00,1.95,16558.0,United Kingdom
19976,581496,22464,HANGING METAL HEART LANTERN,12,2011-12-09 10:20:00,0.79,16558.0,United Kingdom
19977,581497,47566,PARTY BUNTING,5,2011-12-09 10:23:00,10.79,NaN,United Kingdom
19978,581497,23207,LUNCH BAG ALPHABET DESIGN,1,2011-12-09 10:23:00,4.96,NaN,United Kingdom
19979,581498,22960,JAM MAKING SET WITH JARS,5,2011-12-09 10:26:00,8.29,NaN,United Kingdom
19980,581498,20713,JUMBO BAG OWLS,8,2011-12-09 10:26:00,4.13,NaN,United Kingdom
19981,581498,22845,VINTAGE CREAM CAT FOOD CONTAINER,1,2011-12-09 10:26:00,12.46,NaN,United Kingdom
19982,581498,22698,PINK REGENCY TEACUP AND SAUCER,9,2011-12-09 10:26:00,5.79,NaN,United Kingdom
19983,581498,22099,CARAVAN SQUARE TISSUE BOX,2,2011-12-09 10:26:00,2.46,NaN,United Kingdom
19984,581498,85099B,JUMBO BAG RED RETROSPOT,5,2011-12-09 10:26:00,4.13,NaN,United Kingdom
19985,581498,84997b,CHILDRENS CUTLERY RETROSPOT RED,3,2011-12-09 10:26:00,8.29,NaN,United Kingdom
19986,581498,23564,EGG CUP MILKMAID INGRID,1,2011-12-09 10:26:00,2.46,NaN,United Kingdom
19987,581498,21928,JUMBO BAG SCANDINAVIAN BLUE PAISLEY,2,2011-12-09 10:26:00,4.13,NaN,United Kingdom
19988,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,2011-12-09 10:26:00,4.96,NaN,United Kingdom
19989,581502,23270,SET OF 2 CERAMIC PAINTED HEARTS,4,2011-12-09 10:51:00,1.45,15910.0,United Kingdom
19990,581502,22596,CHRISTMAS STAR WISH LIST CHALKBOARD,24,2011-12-09 10:51:00,0.39,15910.0,United Kingdom
19991,581514,22754,SMALL RED BABUSHKA NOTEBOOK,12,2011-12-09 11:20:00,0.21,17754.0,United Kingdom
19992,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom
19993,581574,23238,SET OF 4 KNICK KNACK TINS LONDON,6,2011-12-09 12:09:00,4.15,12526.0,Germany
19994,581578,22736,RIBBON REEL MAKING SNOWMEN,10,2011-12-09 12:16:00,1.65,12713.0,Germany
19995,581578,23255,CHILDRENS CUTLERY CIRCUS PARADE,12,2011-12-09 12:16:00,4.15,12713.0,Germany
19996,581578,22081,RIBBON REEL FLORA + FAUNA,10,2011-12-09 12:16:00,1.65,12713.0,Germany
19997,581579,85099C,JUMBO BAG BAROQUE BLACK WHITE,10,2011-12-09 12:19:00,1.79,17581.0,United Kingdom
19998,581585,22727,ALARM CLOCK BAKELIKE RED,4,2011-12-09 12:31:00,3.75,15804.0,United Kingdom
19999,581585,22481,BLACK TEA TOWEL CLASSIC DESIGN,12,2011-12-09 12:31:00,0.39,15804.0,United Kingdom

# **Statistical summary**

In [9]:
df.describe()

           Quantity     UnitPrice    CustomerID
count  20000.000000  20000.000000  14851.000000
mean       9.511300      4.463227  15295.116692
std       39.946439    116.847348   1716.889608
min    -1296.000000 -11062.060000  12347.000000
25%        1.000000      1.250000  13950.000000
50%        3.000000      2.100000  15184.000000
75%       10.000000      4.130000  16805.000000
max     2400.000000   8142.750000  18283.000000

# 3. Data Quality Check

In [10]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description      50
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     5149
Country           0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(8)

## Quantity Validation

We check for negative and zero quantities because they may represent returns, cancellations, or invalid transactions.

In [13]:
print("Negative Quantity:", (df["Quantity"] < 0).sum())
print("Zero Quantity:", (df["Quantity"] == 0).sum())

Negative Quantity: 365
Zero Quantity: 0

In [15]:
df["InvoiceDate"].dtype

dtype('O')

In [16]:
df["InvoiceDate"] = pd.to_datetime(
    df["InvoiceDate"],
    errors="coerce"
)

df["InvoiceDate"].dtype

dtype('<M8[ns]')

# 4. Data Cleaning

Based on the data quality assessment, the identified issues are handled carefully without removing valid business information unnecessarily.

In [17]:
df = df.drop_duplicates()

print("Rows after removing duplicates:", df.shape[0])

Rows after removing duplicates: 19992

In [18]:
sales_df = df.copy()

In [19]:
sales_df = sales_df[
    (sales_df["Quantity"] > 0) &
    (sales_df["UnitPrice"] > 0)
].copy()

In [20]:
print("Rows after cleaning:", sales_df.shape[0])

Rows after cleaning: 19570

# 5. Feature Engineering

New features are created from the existing data to support sales analysis and provide more useful business information.

In [21]:
sales_df["Revenue"] = (
    sales_df["Quantity"] *
    sales_df["UnitPrice"]
)

In [22]:
sales_df["Revenue"].sum()

np.float64(362902.27999999997)

In [24]:
sales_df["InvoiceMonth"] = (
    sales_df["InvoiceDate"]
    .dt.to_period("M")
    .astype(str)
)

In [25]:
sales_df["OrderType"] = np.where(
    sales_df["InvoiceNo"].astype(str).str.startswith("C"),
    "Cancellation",
    "Sale"
)

In [26]:
sales_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,InvoiceMonth,OrderType
0,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12,Sale
1,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,11.10,2010-12,Sale
2,536382,21832,CHOCOLATE CALCULATOR,12,2010-12-01 09:45:00,1.65,16098.0,United Kingdom,19.80,2010-12,Sale
3,536390,22968,ROSE COTTAGE KEEPSAKE BOX,8,2010-12-01 10:19:00,8.50,17511.0,United Kingdom,68.00,2010-12,Sale
4,536390,84030E,ENGLISH ROSE HOT WATER BOTTLE,24,2010-12-01 10:19:00,3.75,17511.0,United Kingdom,90.00,2010-12,Sale

# 6. Data Validation

After cleaning, the dataset is checked again to confirm that the identified quality issues have been handled correctly.

In [27]:
print("Duplicates:", sales_df.duplicated().sum())

Duplicates: 0

In [28]:
print(
    "Invalid Quantity:",
    (sales_df["Quantity"] <= 0).sum()
)

Invalid Quantity: 0

In [29]:
print(
    "Invalid UnitPrice:",
    (sales_df["UnitPrice"] <= 0).sum()
)

Invalid UnitPrice: 0

In [30]:
sales_df.isnull().sum()

InvoiceNo          0
StockCode          0
Description        0
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID      5044
Country            0
Revenue            0
InvoiceMonth       0
OrderType          0
dtype: int64

In [31]:
sales_df.dtypes

InvoiceNo               object
StockCode               object
Description             object
Quantity                 int64
InvoiceDate     datetime64[ns]
UnitPrice              float64
CustomerID             float64
Country                 object
Revenue                float64
InvoiceMonth            object
OrderType               object
dtype: object

# 7. Data Quality Summary

The dataset was examined for missing values, duplicate records, invalid quantities, invalid prices, and incorrect data types.

Duplicate records were removed to prevent double counting.

Negative quantities and non-positive prices were excluded from the sales analysis because they do not represent normal sales transactions.

Missing CustomerID values were retained because the transactions still contain useful sales information. However, these records should be excluded from customer-level analysis when customer identification is required.

InvoiceDate was converted to datetime format to support time-based analysis.

Two useful features were created: Revenue and InvoiceMonth. Revenue allows direct analysis of sales value, while InvoiceMonth supports monthly sales trend analysis.

After cleaning and validation, the sales dataset is suitable for further sales analysis.

In [32]:
sales_df.to_csv("online_retail_cleaned.csv", index=False)

In [34]:
sales_df.shape

(19570, 11)

In [35]:
sales_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,InvoiceMonth,OrderType
0,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12,Sale
1,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,11.10,2010-12,Sale
2,536382,21832,CHOCOLATE CALCULATOR,12,2010-12-01 09:45:00,1.65,16098.0,United Kingdom,19.80,2010-12,Sale
3,536390,22968,ROSE COTTAGE KEEPSAKE BOX,8,2010-12-01 10:19:00,8.50,17511.0,United Kingdom,68.00,2010-12,Sale
4,536390,84030E,ENGLISH ROSE HOT WATER BOTTLE,24,2010-12-01 10:19:00,3.75,17511.0,United Kingdom,90.00,2010-12,Sale

In [33]:
from google.colab import files

files.download("online_retail_cleaned.csv")